$(function(){
  // $('.home-top').html(
  //     '<div class="w">'
  //     +'<div class="left-nav">您好，欢迎来到生意帮平台!</div>'
  //     +'<div class="right-nav">'
  //       +'<ul>'
  //         +'<li>生意帮首页<span>|</span></li>'
  //         +'<li>供应<span>|</span></li>'
  //         +'<li>求购<span>|</span></li>'
  //         +'<li>关于我们</li>'
  //       +'</ul>'
  //       +'<span class="tel">平台热线： 400-080-0101</span>'
  //     +'</div>'
  //   +'</div>'
  //   )


  $('.search').html(
      '<div class="w">'
      +'<div class="logo">'
        +'<img src="images/t_logo.png" alt="">'
      +'</div>'
      +'<div class="btn">全网询价</div>'
      +'<div class="search-l">'
        +'<div class="input">'
          +'<img src="images/bot-san.png" alt="">'
         +'<input type="text" class="texts" placeholder="请输入搜索关键词">'
          +'<input type="submit" value="搜索" class="search">'
        +'</div>'
      +'</div>'
    +'</div>'
    )


  // $('#foot').html('<div class="w">'
  //             +'<div class="left_f">'
  //                 +'<a href="#"><img src="images/b_logo.png" alt=""></a>'
  //                 +'<ul class="hidden-xs">'
  //                    +' <li><a href="#">首页</a></li>'
  //                     +'<li>|</li>'
  //                     +'<li><a href="#">产品</a></li>'
  //                     +'<li>|</li>'
  //                     +'<li><a href="#">案例分享</a></li>'
  //                     +'<li>|</li>'
  //                     +'<li><a href="#">模板展示</a></li>'
  //                     +'<li>|</li>'
  //                     +'<li><a href="#add_about">关于我们</a></li>'
  //                 +'</ul>'
  //             +'</div>'
  //               +'<div class="middle_f">'
  //                   +'<img src="images/code.png" alt="">'
  //               +'</div>'
  //               +'<div class="right_f">'
  //                   +'<p>全国统一服务热线 : 40000-99990</p>'
  //                   +'<p>E-mail : fang@wayboo.cn</p>'
  //                   +'<p>add : 北京市朝阳区保利东方中心A座17层</p>'
  //                   +'<p>web : www.wayboo.com</p>'
  //                   +'<p>Copyright 2013-2018 www.wayboo.com All Rights Reserved.'
  //                       +'信融科技 版权所有 京IPC备 13035649号-2</p>'
  //               +'</div>'
  //           +'</div>')
  $('#head').html('<div class="w">'
          +'<div class="left-nav">您好，欢迎来到生意帮平台!</div>'
          +'<div class="right-nav">'
            +'<ul>'
             +' <li><a href="http://www.wayboo.org.cn/" target="_blank">生意帮首页</a><span>|</span></li>'
              +'<li><a href="http://www.wayboo.org.cn/buy/" target="_blank">求购</a><span>|</span></li>'
              +'<li><a href="http://www.wayboo.org.cn/sell/" target="_blank">供应</a><span>|</span></li>'
              +'<li><a href="http://www.wayboo.org.cn/about/index.html" target="_blank">关于我们</a></li>'
            +'</ul>'
            +'<div class="tel">平台热线： 400-080-0101</div>'
          +'</div>')
  $('#foot').html('<p><a href="http://www.wayboo.org.cn/" target="_blank">网站首页</a><span>|</span>'
          +'<a href="http://www.wayboo.org.cn/about/index.html" target="_blank">关于我们</a> <span>|</span>'
          +'<a href="http://www.wayboo.org.cn/buy/" target="_blank">求购</a><span>|</span> '
          +'<a href="http://www.wayboo.org.cn/sell/" target="_blank">供应</a></p>'
          +'<p>平台热线：400-080-0101 周一至周五（9:00～21:00） 邮箱：2824428156@qq.com</p>'
          +'<p>Copyright 2013-2019 www.wayboo.org.cn All Rights Reserved. 生意帮平台 版权所有 沪ICP备14037130号-1</p>'
          +'<p>免责声明：以上所展示的信息由企业自行提供，内容的真实性、准确性和合法性由发布企业负责。生意帮平台对此不承担任何保证责任。</p>')
})